version: 2.1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - testing
      - deploy:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  testing:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
      - run:
          name: run tests
          command: |
            make tests
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*